name: App Suggestion
title: EDIT ME Include the app name
description: Suggest an app to be added Pi-Apps. pi-apps developers may choose to assist in adding your app suggestion.
labels: App Request
body:
  - type: input
    id: app-name
    attributes:
      label: What is the name of the app?
      placeholder: Ex - Zoom, AndroidBuddy
    validations:
      required: true
      
  - type: textarea
    id: host
    attributes:
      label: Where is the app hosted?
      placeholder: Ex - Github link, Gitlab link, Sourceforge link, Website
    validations:
      required: true
  
  - type: textarea
    id: about
    attributes:
      label: About the app
      description: What is its main purpose? How does it work? 
      placeholder: Tell us about the app here!
    validations:
      required: true
      
  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      description: All of the following MUST be met. If you can NOT check one of these boxes. Then do NOT create a GitHub Issue. We will close it. The checkboxes are made a requirement on purpose.
      options:
        - label: I have confirmed that this app is legal and not piracy.
          required: true
        - label: I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
          required: true  
        - label: I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
          required: true
        - label: I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).
          required: true
