name: sha1sum
on:
  workflow_dispatch:
jobs:
  sha1sum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pi-apps repo
        uses: actions/checkout@v4
      - name: hash all files
        run: |
          cd $GITHUB_WORKSPACE
          find . -path ./.git -prune -o -type f -exec sha1sum "{}" +
